module.exports = {
  alternateBaseUrls: [],
  buildId: "",
  dest: "public",
  dev: true,
  distDir: `${process.cwd()}/dist`,
  dir: process.cwd(),
  excludedPaths: [],
  extraPaths: [],
  exportPathMap: undefined,
  exportTrailingSlash: false,
  outDir: `${process.cwd()}/out`,
  pageExtensions: ["js"],
  pages: "pages",
  pageTags: [],
  robotsFilename: "robots.txt",
  sitemapFilename: "sitemap.xml",
  robots: true,
  sitemap: true,
};
